# Generated by Django 3.1.7 on 2021-03-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210311_2245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='post',
            name='descripcion',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default=' '),
        ),
    ]
