# Generated by Django 3.1.7 on 2021-03-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_infromacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('descripcion', models.TextField(default='')),
                ('infromacion', models.TextField(default='')),
            ],
        ),
    ]
