# Generated by Django 3.1.7 on 2021-03-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_informacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('descripcion', models.TextField(default='')),
                ('infromacion', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Informacion3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('descripcion', models.TextField(default='')),
                ('infromacion', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Informacion4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('descripcion', models.TextField(default='')),
                ('infromacion', models.TextField(default='')),
            ],
        ),
    ]
